=== sDebski/XML/7. XSD+XML - lab7/zad6.xsd
<xsd:schema xmlns:xsd=
"http://www.w3.org/2001/XMLSchema">
  <xsd:element name="zamowienie" type="zamowienie_type" />

  <xsd:complexType name="zamowienie_type">
    <xsd:sequence>
      <xsd:element name="adres" type="adres_type" />
      <xsd:element name="artykuly" type="artykuly_type" />
    </xsd:sequence>
    <xsd:attribute name="numer_zamowienia" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="adres_type">
    <xsd:sequence>
      <xsd:element name="miejsce" type="xsd:string" />
      <xsd:element name="ulica" type="xsd:string" minOccurs="0" />
      <xsd:element name="kod_pocztowy" type="kod_pocztowy_type"/>
    </xsd:sequence>
    <xsd:attribute name="termin_dostarczenia" type="xsd:string" use="required"/>
    <xsd:attribute name="kraj" type="xsd:string" use="required"/>
  </xsd:complexType>


  <xsd:simpleType name="kod_pocztowy_type">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9]{2}[-][0-9]{3}" />
    </xsd:restriction>
  </xsd:simpleType>


  <xsd:complexType name="artykuly_type">
    <xsd:sequence>
      <xsd:element name="artykul" type="artykul_type" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="artykul_type">
    <xsd:sequence>
      <xsd:element name="film" type="film_type" minOccurs="0" />
      <xsd:element name="ksiazka" type="ksiazka_type" minOccurs="0" />
      <xsd:element name="plyta" type="plyta_type" minOccurs="0" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="film_type">
    <xsd:sequence>
      <xsd:element name="tytul" type="xsd:string" />
      <xsd:element name="autor" type="xsd:string" />
      <xsd:element name="rok_wydania" type="xsd:string"/>
      <xsd:element name="czas_trwania" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>


  <xsd:complexType name="ksiazka_type">
    <xsd:sequence>
      <xsd:element name="tytul" type="xsd:string" />
      <xsd:element name="autor" type="xsd:string" />
      <xsd:element name="rok_wydania" type="xsd:string"/>
      <xsd:element name="nr_wydania" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>


  <xsd:complexType name="plyta_type">
    <xsd:sequence>
      <xsd:element name="tytul" type="xsd:string" />
      <xsd:element name="wykonawca" type="xsd:string" />
      <xsd:element name="wydawca" type="xsd:string"/>
      <xsd:element name="rok_wydania" type="xsd:string" />
      <xsd:element name="czas_trwania" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== sDebski/XML/7. XSD+XML - lab7/zad6.xml
<?xml version="1.0" encoding="utf-8"?>
<zamowienie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="zad6.xsd" numer_zamowienia="n1">
  <adres termin_dostarczenia='10-10-2010' kraj='Polska'>
    <miejsce>Szpital</miejsce>
    <ulica>Komara</ulica>
    <kod_pocztowy>12-123</kod_pocztowy>
  </adres>
  <artykuly>
    <artykul id="a1">
      <film>
        <tytul>Lord</tytul>
        <autor>Peter Jackson</autor>
        <rok_wydania>01-01-2001</rok_wydania>
        <czas_trwania>2 h</czas_trwania>
      </film>
    </artykul>
    <artykul id="a2">
      <ksiazka>
        <tytul>Manamam</tytul>
        <autor>Man Manar</autor>
        <rok_wydania>02-02-2002</rok_wydania>
        <nr_wydania>100</nr_wydania>
      </ksiazka>
    </artykul>
    <artykul id="a3">
      <plyta>
        <tytul>Mocna</tytul>
        <wykonawca>Dr. Autor</wykonawca>
        <wydawca>Si-Studio</wydawca>
        <rok_wydania>03-03-2003</rok_wydania>
        <czas_trwania>1 h</czas_trwania>
      </plyta>
    </artykul>
  </artykuly>
</zamowienie>
