<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE silownia [

  <!ENTITY  gda "Gdansk">
  <!ENTITY  gdy "Gdynia">
  <!ENTITY  a "Anna">
  <!ENTITY  ulica "ul.">
  <!ENTITY  n "Natalia">
  <!ENTITY  z "Zajęcia">


  
  <!ELEMENT silownia (adres_silowni, wlasciciel, trenerzy, klienci, sale, zajecia, sprzety)>
  <!ATTLIST silownia nazwa NMTOKENS #REQUIRED>

  <!ELEMENT adres_silowni (miasto, ulica?, numer, kod, nic)>
  <!ATTLIST nic nic NMTOKEN #IMPLIED>
  <!ELEMENT wlasciciel (imie, nazwisko, adres)>

  <!ELEMENT adres (miasto, ulica?, numer, kod)>

  <!ELEMENT trenerzy ((trener)*)>
  <!ELEMENT klienci ((klient)*)>
  <!ELEMENT sale ((sala)*)>
  <!ELEMENT zajecia ((zajecie)*)>
  <!ELEMENT sprzety ((sprzet)*)>


  <!ELEMENT trener ((imie)+, nazwisko, pesel, adres)>
  <!ATTLIST trener plec (k|m) #REQUIRED >
  <!ATTLIST trener id ID #REQUIRED >

  <!ELEMENT klient (imie, nazwisko, pesel, waznosc_karnetu, adres)>
  <!ELEMENT waznosc_karnetu (od_kiedy, do_kiedy)>

  <!ELEMENT od_kiedy (#PCDATA)>
  <!ELEMENT do_kiedy (#PCDATA)>

  <!ATTLIST klient id ID #REQUIRED>
  <!ATTLIST klient plec (k|m|b) "b">

  <!ELEMENT sala (nazwa, powierzchnia)>
  <!ATTLIST sala id ID #REQUIRED>

  <!ATTLIST powierzchnia jednostka CDATA #FIXED "m2">

  <!ELEMENT zajecie (czas_trwania, dzien_tygodnia+, godzina, opis)>
  <!ATTLIST zajecie idTrener IDREF #REQUIRED>
  <!ATTLIST zajecie idSala IDREF #REQUIRED>

  <!ATTLIST czas_trwania jednostka NMTOKEN #FIXED "minuty">

  <!ELEMENT sprzet (nazwa, firma, ilosc, opis*)>



  <!ELEMENT miasto (#PCDATA)>
  <!ELEMENT ulica (#PCDATA)>
  <!ELEMENT kod (#PCDATA)>
  <!ELEMENT imie (#PCDATA)>
  <!ELEMENT nazwisko (#PCDATA)>
  <!ELEMENT pesel (#PCDATA)>
  <!ELEMENT numer (#PCDATA)>
  <!ELEMENT nazwa (#PCDATA)>
  <!ELEMENT firma (#PCDATA)>
  <!ELEMENT ilosc (#PCDATA)>
  <!ELEMENT dzien_tygodnia (#PCDATA)>
  <!ELEMENT godzina (#PCDATA)>
  <!ELEMENT czas_trwania (#PCDATA)>
  <!ELEMENT opis (#PCDATA)>
  <!ELEMENT powierzchnia (#PCDATA)>



  <!ELEMENT nic EMPTY>




]>

<?xml-stylesheet type="text/css" href="style.css" ?>
<silownia nazwa="Sport Connect">
  <adres_silowni>
    <miasto>&gda;</miasto>
    <ulica>&ulica; Jagielonska</ulica>
    <numer>37</numer>
    <kod>83-330</kod>
    <nic nic="nic"/>
  </adres_silowni>
  <wlasciciel>
    <imie>Oleg</imie>
    <nazwisko>Olegowic</nazwisko>
    <adres>
      <miasto>Warszawa</miasto>
      <ulica>&ulica; Dworska</ulica>
      <numer>1</numer>
      <kod>50-512</kod>
    </adres>
  </wlasciciel>
  <trenerzy>
    <trener plec="m" id="t1">
      <imie>Adam</imie>
      <imie>Bartosz</imie>
      <nazwisko>Adamowicz</nazwisko>
      <pesel>89101002234</pesel>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Slowackiego</ulica>
        <numer>10</numer>
        <kod>10-550</kod>
      </adres>
    </trener>
    <trener plec="m" id="t2">
      <imie>Marian</imie>
      <nazwisko>Marianowicz</nazwisko>
      <pesel>85101002534</pesel>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Slowackiego</ulica>
        <numer>15</numer>
        <kod>10-550</kod>
      </adres>
    </trener>
    <trener plec="k" id="t3">
      <imie>&a;</imie>
      <nazwisko>Aniowicz</nazwisko>
      <pesel>93040512345</pesel>
      <adres>
        <miasto>&gdy;</miasto>
        <ulica>&ulica; Zawiszy</ulica>
        <numer>54</numer>
        <kod>15-850</kod>
      </adres>
    </trener>
    <trener plec="k" id="t4">
      <imie>Aleksandra</imie>
      <nazwisko>Olowicz</nazwisko>
      <pesel>90020312345</pesel>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Bora</ulica>
        <numer>80</numer>
        <kod>10-570</kod>
      </adres>
    </trener>
  </trenerzy>
  <klienci>
    <klient id="k1" plec="b">
      <imie>&n;</imie>
      <nazwisko>Natalowicz</nazwisko>
      <pesel>90020312395</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-03-10</od_kiedy>
        <do_kiedy>2019-05-06</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Bora</ulica>
        <numer>70</numer>
        <kod>10-570</kod>
      </adres>
    </klient>
    <klient id="k2" plec="b">
      <imie>Marta</imie>
      <nazwisko>Martowicz</nazwisko>
      <pesel>93020382345</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-02-10</od_kiedy>
        <do_kiedy>2019-05-05</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Bora</ulica>
        <numer>90</numer>
        <kod>10-570</kod>
      </adres>
    </klient>
    <klient id="k3" plec="k">
      <imie>Nadia</imie>
      <nazwisko>Nadowicz</nazwisko>
      <pesel>98020312345</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-04-21</od_kiedy>
        <do_kiedy>2019-06-13</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>Sopot</miasto>
        <ulica>&ulica; Olewna</ulica>
        <numer>5</numer>
        <kod>20-202</kod>
      </adres>
    </klient>
    <klient id="k4" plec="m">
      <imie>Witold</imie>
      <nazwisko>Witoldowicz</nazwisko>
      <pesel>83122112345</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-04-10</od_kiedy>
        <do_kiedy>2019-07-05</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>&gdy;</miasto>
        <ulica>&ulica; Trubadurow</ulica>
        <numer>136</numer>
        <kod>25-554</kod>
      </adres>
    </klient>
    <klient id="k5" plec="m">
      <imie>Marcin</imie>
      <nazwisko>Marcinowicz</nazwisko>
      <pesel>79091912345</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-04-15</od_kiedy>
        <do_kiedy>2019-05-05</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Miodowa</ulica>
        <numer>50</numer>
        <kod>10-560</kod>
      </adres>
    </klient>
    <klient id="k6" plec="b">
      <imie>Aleksandra</imie>
      <nazwisko>Olowicz</nazwisko>
      <pesel>90020312345</pesel>
      <waznosc_karnetu>
        <od_kiedy>2019-02-10</od_kiedy>
        <do_kiedy>2019-05-05</do_kiedy>
      </waznosc_karnetu>
      <adres>
        <miasto>&gda;</miasto>
        <ulica>&ulica; Bora</ulica>
        <numer>80</numer>
        <kod>10-570</kod>
      </adres>
    </klient>
  </klienci>
  <sale>
    <sala id="s1">
      <nazwa>Sala Crossfit</nazwa>
      <powierzchnia jednostka="m2">120</powierzchnia>
    </sala>
    <sala id="s2">
      <nazwa>Sala Ciezarowa</nazwa>
      <powierzchnia jednostka="m2">200</powierzchnia>
    </sala>
    <sala id="s3">
      <nazwa>Sala Zajeciowa 1</nazwa>
      <powierzchnia jednostka="m2">100</powierzchnia>
    </sala>
    <sala id="s4">
      <nazwa>Sala Zajeciowa 2</nazwa>
      <powierzchnia jednostka="m2">80</powierzchnia>
    </sala>
  </sale>
  <zajecia>
    <zajecie idTrener="t1" idSala="s2">
      <czas_trwania jednostka="minuty">120</czas_trwania>
      <dzien_tygodnia>Czwartek</dzien_tygodnia>
      <godzina>18:00</godzina>
      <opis>&z; przygotowujące do Trojboju silowego</opis>
    </zajecie>
    <zajecie idTrener="t2" idSala="s1">
      <czas_trwania jednostka="minuty">120</czas_trwania>
      <dzien_tygodnia>Środa</dzien_tygodnia>
      <godzina>16:00</godzina>
      <opis>
        &z; Crosfitowe wzmacniające motorykę
      </opis>
    </zajecie>
    <zajecie idTrener="t3" idSala="s3">
      <czas_trwania jednostka="minuty">60</czas_trwania>
      <dzien_tygodnia>Piątek</dzien_tygodnia>
      <godzina>19:00</godzina>
      <opis>&z; z Zumby</opis>
    </zajecie>
    <zajecie idTrener="t4" idSala="s4">
      <czas_trwania jednostka="minuty">60</czas_trwania>
      <dzien_tygodnia>Piątek</dzien_tygodnia>
      <godzina>20:00</godzina>
      <opis>&z; na rowerkach</opis>
    </zajecie>
  </zajecia>
  <sprzety>
    <sprzet>
      <nazwa>Hantle</nazwa>
      <firma>Szultka</firma>
      <ilosc>40</ilosc>
      <opis>Hantle z przedzialu ciezarowego 2-20kg</opis>
      <opis>2 hantle na kazda wage, roznica = 2kg</opis>
    </sprzet>
    <sprzet>
      <nazwa>Sztanga</nazwa>
      <firma>Szultka</firma>
      <ilosc>4</ilosc>
      <opis>Sztangi o dlugosci 1.5m i wadze 20kg</opis>
    </sprzet>
    <sprzet>
      <nazwa>Ławeczka płaska</nazwa>
      <firma>Szultka</firma>
      <ilosc>4</ilosc>
      <opis>Ławeczka płaska, kolor obicia zielony</opis>
    </sprzet>
    <sprzet>
      <nazwa>ławeczka płaska regulowana</nazwa>
      <firma>Szultka</firma>
      <ilosc>2</ilosc>
      <opis>Ławeczka płaska, kolor obicia czerwony, regulowowana</opis>
    </sprzet>
    <sprzet>
      <nazwa>Talerze ciężarowe</nazwa>
      <firma>Szultka</firma>
      <ilosc>30</ilosc>
      <opis>Talerze ciężarowe, przedział wagowy 5-25kg</opis>
      <opis> roznica = 5kg, kazdego 6 sztuk</opis>
    </sprzet>
  </sprzety>
</silownia>
