=== sDebski/XML/4. DTD+XML - lab4/zad7.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY % Stara_matura "IGNORE">
<!ENTITY % Nowa_matura "INCLUDE">
<!ENTITY % pc "#PCDATA">

<!ELEMENT matura (przedmiot*)>

<![%Stara_matura; [
<!ELEMENT przedmiot (nazwa, ocena)>
<!ATTLIST przedmiot wynik (zal|nzal) #REQUIRED>
<!ELEMENT ocena (%pc;)>
]]>

<![%Nowa_matura; [ 
<!ELEMENT przedmiot (nazwa, punkty)>
<!ELEMENT punkty (%pc;)>
<!ATTLIST przedmiot procent CDATA "0%">
<!ATTLIST przedmiot poziom (podstawowy|rozszerzony) "podstawowy">

]]>

<!ELEMENT nazwa (%pc;)>

=== sDebski/XML/4. DTD+XML - lab4/zad7.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE matura SYSTEM "zad7.dtd">

<matura>
	<przedmiot procent="58%" poziom="podstawowy">
		<nazwa>Matematyka</nazwa>
		<punkty>29</punkty>
	</przedmiot>
	<przedmiot procent="37%" poziom="rozszerzony">
		<nazwa>Biologia</nazwa>
		<punkty>74</punkty>
	</przedmiot>
	<przedmiot procent="80%" poziom="podstawowy">
		<nazwa>Angielski</nazwa>
		<punkty>40</punkty>
	</przedmiot>
	<przedmiot procent="90%" poziom="podstawowy">
		<nazwa>Polski</nazwa>
		<punkty>45</punkty>
	</przedmiot>
</matura>
