=== sDebski/XML/lab4/zad4.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ENTITY % el3 "element1">
<!ENTITY % el2 "element2">
<!ENTITY % el1 "#PCDATA">


<!ELEMENT glowny (%el1;|%el2;|%el3;)* >
<!ELEMENT element1 (#PCDATA) >
<!ELEMENT element2 (#PCDATA)>

=== sDebski/XML/lab4/zad4.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE glowny SYSTEM "zad4.dtd">

<glowny>
	<element1>cos</element1>
	<element2>cos</element2>
	napis
	<element2>cos</element2>
	<element2>cos</element2>
	napis2
	<element1>cos</element1>
	<element2>cos</element2>
	<element1>cos</element1>
</glowny>
