=== sDebski/XML/lab3/zad6.dtd
<!ELEMENT zamowienie (adres, produkty)>
<!ATTLIST zamowienie numer_zamowienia CDATA #REQUIRED>
<!ELEMENT adres (miejsce, ulica, kod_pocztowy)>
<!ELEMENT ulica (#PCDATA)>
<!ATTLIST adres termin_dostarczenia CDATA #IMPLIED>
<!ATTLIST adres kraj (Polska) #FIXED "Polska">
<!ELEMENT produkty (artykuly)>
<!ELEMENT artykuly (artykul+)>
<!ELEMENT artykul (film|ksiazka|plyta)>
<!ATTLIST artykul id ID #REQUIRED>
<!ELEMENT film (tytul, rezyser, rok_wydania, czas_trwania)>
<!ELEMENT ksiazka (tytul, autor, rok_wydania, nr_wydania)>
<!ELEMENT plyta (tytul, wykonawca, wydawca, rok_wydania)>
<!ELEMENT miejsce (#PCDATA)>
<!ELEMENT kod_pocztowy (#PCDATA)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT rezyser (#PCDATA)>
<!ELEMENT rok_wydania (#PCDATA)>
<!ELEMENT czas_trwania (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT nr_wydania (#PCDATA)>
<!ELEMENT wykonawca (#PCDATA)>
<!ELEMENT wydawca (#PCDATA)>
<!ELEMENT miejsc (#PCDATA)>

=== sDebski/XML/3. DTD+XML - lab3/zad6.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE zamowienie SYSTEM "zad6.dtd">
<zamowienie numer_zamowienia="32">
	<adres termin_dostarczenia="10.05.2019" kraj="Polska">
		<miejsce>Domek nad jeziorem</miejsce>
		<ulica>Złota</ulica>
		<kod_pocztowy>83-330</kod_pocztowy>
	</adres>	
	<produkty>
		<artykuly>
			<artykul id="p54">
				<film>
					<tytul>Lord of the Rings</tytul>
					<rezyser>Peter Jackson</rezyser>
					<rok_wydania>2000</rok_wydania>
					<czas_trwania>140 minut</czas_trwania>
				</film>
			</artykul>
			<artykul id="u23">
				<ksiazka>
					<tytul>Wiedźmin</tytul>
					<autor>Andrzej Sapkowski</autor>
					<rok_wydania>2003</rok_wydania>
					<nr_wydania>14526</nr_wydania>
				</ksiazka>
			</artykul>
		</artykuly>
	</produkty>
</zamowienie>
