=== sDebski/XML/lab7/zad1.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:attribute name="plec">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="M"/>
				<xsd:enumeration value="K"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>



        <xsd:element name="osoba">
                <xsd:complexType>
                        <xsd:sequence>
                                <xsd:element name="imie" type="xsd:string"/>
                                <xsd:element name="nazwisko" type="xsd:string"/>
                        </xsd:sequence>
			<xsd:attribute ref="plec" use="required"/>
                </xsd:complexType>
        </xsd:element>

	<xsd:element name="ludzie">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="nauczyciele" type="n_type"/>
				<xsd:element name="uczniowie" type="u_type"/>
				<xsd:element name="pozostali" type="p_type"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:complexType name="n_type">
		<xsd:sequence>
			<xsd:element ref="osoba" />
		</xsd:sequence>
	</xsd:complexType>


        <xsd:complexType name="u_type">
                <xsd:sequence>
                        <xsd:element ref="osoba" />
                </xsd:sequence>
        </xsd:complexType>


        <xsd:complexType name="p_type">
                <xsd:sequence>
                        <xsd:element ref="osoba" />
                </xsd:sequence>
        </xsd:complexType>

</xsd:schema>

=== sDebski/XML/lab7/zad1.xml
<?xml version='1.0' encoding='UTF-8'?>
<ludzie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zad1.xsd">
	<nauczyciele>
		<osoba plec="K">
			<imie>Maria</imie>
			<nazwisko>Kowalska</nazwisko>
		</osoba>
	</nauczyciele>
	<uczniowie>
		<osoba plec="M">
                        <imie>Jan</imie>
                        <nazwisko>Je≈º</nazwisko>
		</osoba>
	</uczniowie>
	<pozostali>
		<osoba plec="M">
                        <imie>Marcin</imie>
                        <nazwisko>Porost</nazwisko>
		</osoba>
	</pozostali>
</ludzie>
